//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapiensIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountVouchers
    {
        public int DiscountVoucherID { get; set; }
        public string VoucherTitle { get; set; }
        public string VoucherCode { get; set; }
        public string VoucherDecription { get; set; }
        public string VoucherImage { get; set; }
        public Nullable<double> DiscountPercentage { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<bool> IsLabApplicable { get; set; }
        public Nullable<bool> IsMedicineApplicable { get; set; }
        public Nullable<bool> IsAppointmentApplicable { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public System.DateTime AddedDateTime { get; set; }
        public bool Status { get; set; }
    }
}
