//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapiensIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialities
    {
        public int SpecialityID { get; set; }
        public string SpecialityTitle { get; set; }
        public string DisplayPicture { get; set; }
        public bool Status { get; set; }
    }
}
